export const CREATE_AGENT_LOADING = "CREATE_AGENT_LOADING";
export const CREATE_AGENT_SUCCESS = "CREATE_AGENT_SUCCESS";
export const CREATE_AGENT_ERROR = "CREATE_AGENT_ERROR";

// oN lOGIN aGENT

export const LOGN_AGENT_LOADING = "LOGN_AGENT_LOADING";
export const LOGN_AGENT_SUCCESS = "LOGN_AGENT_SUCCESS";
export const LOGN_AGENT_ERROR = "LOGN_AGENT_ERROR";
