export const CREATE_BOOKING_API_LOADING = "CREATE_BOOKING_API_LOADING"
export const CREATE_BOOKING_API_ERROR = "CREATE_BOOKING_API_ERROR"
export const CREATE_BOOKING_API_SUCCESS = "CREATE_BOOKING_API_SUCCESS"