export const CREATE_CONTACTUS_API_LOADING = "CREATE_CONTACTUS_API_LOADING"
export const CREATE_CONTACTUS_API_ERROR = "CREATE_CONTACTUS_API_ERROR"
export const CREATE_CONTACTUS_API_SUCCESS = "CREATE_CONTACTUS_API_SUCCESS"