export const CREATE_ENQUIRY_API_LOADING = "CREATE_ENQUIRY_API_LOADING"
export const CREATE_ENQUIRY_API_ERROR = "CREATE_ENQUIRY_API_ERROR"
export const CREATE_ENQUIRY_API_SUCCESS = "CREATE_ENQUIRY_API_SUCCESS"