
export const GET_ALL_COLLECTION_API_LOADING = 'GET_ALL_COLLECTION_API_LOADING'
export const GET_ALL_COLLECTION_API_SUCCESS = 'GET_ALL_COLLECTION_API_SUCCESS'
export const GET_ALL_COLLECTION_API_ERROR = 'GET_ALL_COLLECTION_API_ERROR'