export const LOCATION_GET_API_LOADING = "LOCATION_GET_API_LOADING";
export const LOCATION_GET_API_SUCCESS = "LOCATION_GET_API_SUCCESS";
export const LOCATION_GET_API_ERROR = "LOCATION_GET_API_ERROR";
