
export const GET_BOOKING_OFFER_LOADING = "GET_BOOKING_OFFER_LOADING"
export const GET_BOOKING_OFFER_ERROR = "GET_BOOKING_OFFER_ERROR"
export const GET_BOOKING_OFFER_SUCCESS = "GET_BOOKING_OFFER_SUCCESS"

export const GET_ALL_OFFER_API_LOADING = 'GET_ALL_OFFER_API_LOADING'
export const GET_ALL_OFFER_API_SUCCESS = 'GET_ALL_OFFER_API_SUCCESS'
export const GET_ALL_OFFER_API_ERROR = 'GET_ALL_OFFER_API_ERROR'