
export const GET_BOOKING_OFFER_LOADING = "GET_BOOKING_OFFER_LOADING"
export const GET_BOOKING_OFFER_ERROR = "GET_BOOKING_OFFER_ERROR"
export const GET_BOOKING_OFFER_SUCCESS = "GET_BOOKING_OFFER_SUCCESS"