export const GET_ROOMS_ALL_API_LOADING = "GET_ROOMS_ALL_API_LOADING";
export const GET_ROOMS_ALL_API_SUCCESS = "GET_ROOMS_ALL_API_SUCCESS";
export const GET_ROOMS_ALL_API_ERROR = "GET_ROOMS_ALL_API_ERROR";
